### PR TITLE
Update drastically shortens the needed code

### PR DESCRIPTION
**Pull request by ghost**
As ezraverheijen showed on the Kirby forum here: https://forum.getkirby.com/t/kirbytext-markdown-without-p-element/438/5 there is a much simpler way to reach the same goal, without using "slow" regex.

### CODE REVIEW

**Comment by jbeyerstedt** [comment]
I just tested the old version and your approach and noticed, that the current version removes all `<p>` and `</p>` tags. And currently I'm thinking, that this not intended. But I also don't know, what I had in mind, when I released this plugin.

The first problem I have with your approach is, that the behavior of the plugin is changed.
And I don't know, if anybody relies on the current behavior.
But otherwise, it shouldn't be an issue, because the main use case is a single line of text with kirby tags in it.
So the current behavior would be "wrong".

But if someone uses `kirbytextRaw` on a text area, which start with a heading or list, your approach would break the first three characters ignoring the fact, that these are not a `<p>` tag.

Do you think this will be an issue? I only see my use case and it wouldn't be an issue there. But I don't know, how others will use it.

**Comment by jbeyerstedt** [comment]
A saver way to use the substring approach would be to check, if the first characters are `<p>` and the last ones are `</p>` before cutting them off. Otherwise the kirbytext()-string will be returned unchanged.
```php
$text = kirbytext($field->value);
if (str::substr($text, 0, 3) === '<p>' && str::substr($text, -4) === '</p>') {
  return str::substr($text, 3, -4);
} else {
  return $text;
}
```
(This might be invalid php, but I'm in C++ mode currently with several university projects.)
What do you think? Sadly, it isn't the short solution any more.

Anyway: Could you update the version numbers to 1.1.0 for me please. In all three files.
And perhaps add a little sentence to the readme:
> Attention: The behavior of this plugin might have changed in some edge cases with version 1.1.0.

**Comment by ghost** [comment]
Let me update the code to take your observations into account! 👍

**Comment by ghost** [comment]
Bumped the version number and added your code. Works fine! 👍

**Comment by jbeyerstedt** [comment]
Thank you for the improvement and sorry for the delay. Exams are taking my time.

**Pull request merged**
